server:
  port: 80

#??druid???
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie
      username: root
      password: 1234
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0

#??mybatisplus
mybatis-plus:
  configuration:
    #??????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #??mybatis????????????
  global-config:
    db-config:
      id-type: assign_id

reggie:
 path: G:\img\






